name: Deploy to Server

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/dokanSathi
            
            # Use absolute paths or export the path manually
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"
            
            # Now run the commands
            git pull origin main
            bun install
            bun run build
            
            # Standard Laravel tasks
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan optimize
            
            # Reset permissions so Nginx can read the new build files
            sudo chown -R www-data:www-data .
            sudo chmod -R 775 storage bootstrap/cache